import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const source = await readFile(new URL("../js/scoreboardRooms.js", import.meta.url), "utf8");
const { ScoreboardRoom, roomStorageKey } = await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
const initial = { names: ["A", "B"], points: [0, 0], wins: [0, 0], history: [], breakPlayer: 0, strokeScore: 0 };
const values = new Map();
const storage = { getItem: (key) => values.get(key), setItem: (key, value) => values.set(key, value) };
const code = "000123";
storage.setItem(roomStorageKey(code), JSON.stringify({ token: "private" }));
let calls = [];
let handler = async () => ({ estado: initial, versao: 1, encerrada: false, controle_ativo: true });
const create = (viewer = false) => new ScoreboardRoom({ code, viewer, storage, onChange() {}, request: async (payload) => { calls.push(structuredClone(payload)); return handler(payload); } });
const client = create();
await client.tick(); clearTimeout(client.timer);
assert.equal(client.editable, true);
handler = async () => { throw new Error("Lost response"); };
const changed = structuredClone(initial); changed.points[0] = 7;
client.submit(changed);
await new Promise((resolve) => setTimeout(resolve, 0)); clearTimeout(client.timer);
assert.equal(client.editable, false);
assert.equal(client.submit(changed), false);
const pending = structuredClone(client.pending);
client.stop();
const restored = create();
assert.deepEqual(restored.pending, pending);
handler = async () => ({ estado: changed, versao: 2, encerrada: false, repetido: true });
await restored.tick(); clearTimeout(restored.timer);
assert.deepEqual(calls.at(-1), pending, "retry must keep UUID, version and content");
assert.equal(restored.state.points[0], 7);
assert.equal(restored.pending, null);
assert.equal(restored.undoStack.length, 1);
handler = async () => ({ estado: initial, versao: 3, encerrada: false });
assert.equal(restored.undo(), true);
assert.equal(restored.undo(), false, "cannot undo again while awaiting acknowledgement");
await new Promise((resolve) => setTimeout(resolve, 0)); clearTimeout(restored.timer);
assert.equal(restored.state.points[0], 0);
assert.equal(restored.undoStack.length, 0);
assert.equal(restored.undo(), false);
handler = async () => ({ versao: 3, estado: changed, encerrada: false, controle_ativo: false });
await restored.tick(); clearTimeout(restored.timer);
assert.equal(restored.editable, false);
assert.equal(restored.token, "");
restored.stop();
storage.setItem(roomStorageKey(code), JSON.stringify({ token: "private" }));
const viewer = create(true);
await viewer.tick(); clearTimeout(viewer.timer);
assert.equal(viewer.editable, false);
assert.equal(calls.at(-1).controller_token, undefined);
viewer.stop();
const conflict = create();
handler = async () => ({ estado: initial, versao: 3, encerrada: false, controle_ativo: true });
await conflict.tick(); clearTimeout(conflict.timer);
handler = async () => { throw Object.assign(new Error("Conflict"), { status: 409 }); };
conflict.submit(changed);
await new Promise((resolve) => setTimeout(resolve, 0)); clearTimeout(conflict.timer);
assert.equal(conflict.pending, null);
assert.equal(conflict.version, 0);
assert.equal(conflict.editable, false);
handler = async () => { throw Object.assign(new Error("Expired"), { status: 410 }); };
await conflict.tick();
assert.equal(conflict.closed, true);
assert.equal(conflict.token, "");
conflict.stop();
assert.equal(values.has("aec_sinuca_placar"), false, "rooms must not write the local game");
console.log("OK: recovery, immutable retry, serialization, revocation, viewer, conflict, expiry and local isolation");
